---
- name: "Wordpress installation/configuration"
  hosts: amazon
  become: true
  vars_files: 
    - variables.vars
        
  tasks:
    
    
    - name: "Apache installation"
      yum:
        name: "{{packages}}"
        state: present

    - name: "Apache - Creating vhost /etc/httpd/conf.d/default.conf"
      template:
        src: vhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"

    - name: "Apache - Creating documentroot /var/www/html/{{ domain_name }}"
      file:
        path: "/var/www/html/{{ domain_name }}"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"

    - name: "Apache - Creating test.html & test.php"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ domain_name }}"
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
      with_items:
        - info.php
        - test.html
    
    - name: "Apache - PHP installation"
      shell: amazon-linux-extras install php7.4 -y
      
    
    - name: "Apache - Restarting-enabling PHP-FPM"
      service:
        name: php-fpm
        state: restarted
        enabled: true
            
    
    - name: "Apache -Restarting-enabling httpd"
      service:
        name: httpd
        state: restarted
        enabled: true