---
- name: "Wordpress installation/configuration"
  hosts: amazon
  become: true
  vars_files: 
    - variables.vars
        
  tasks:
    
    
    - name: "Apache installation"
      yum:
        name: "{{packages}}"
        state: present

    - name: "Apache - Creating vhost /etc/httpd/conf.d/default.conf"
      template:
        src: vhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"

    - name: "Apache - Creating documentroot /var/www/html/{{ domain_name }}"
      file:
        path: "/var/www/html/{{ domain_name }}"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"