---
- name: "Wordpress installation/configuration"
  hosts: amazon
  become: true
  vars_files: 
    - variables.vars
        
  tasks:
    
    
    - name: "Apache installation"
      yum:
        name: "{{packages}}"
        state: present

    - name: "Apache - Creating vhost /etc/httpd/conf.d/default.conf"
      template:
        src: vhost.conf.tmpl
        dest: /etc/httpd/conf.d/default.conf
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"

    - name: "Apache - Creating documentroot /var/www/html/{{ domain_name }}"
      file:
        path: "/var/www/html/{{ domain_name }}"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"

    - name: "Apache - Creating test.html & test.php"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ domain_name }}"
        owner: "{{ apache_user }}"
        group: "{{ apache_group }}"
      with_items:
        - info.php
        - test.html
    
    - name: "Apache - PHP installation"
      shell: amazon-linux-extras install php7.4 -y
      
    
    - name: "Apache - Restarting-enabling PHP-FPM"
      service:
        name: php-fpm
        state: restarted
        enabled: true
            
    
    - name: "Apache -Restarting-enabling httpd"
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "Mariadb installation"
      yum:
        name: 
          - mariadb-server
          - MySQL-python
        state: present
            
    - name: "Mariadb service -Restarting-enabling mariadb service"
      service:
        name: mariadb
        state: restarted
        enabled: true
            
    - name: "Mariadb -Root passsword setup"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        name: "root"
        password: "{{ mysql_root_pass }}"
        host_all: true
            
    - name: "Mariadb -Removing Anonymous Users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_pass }}"
        name: ""
        state: absent
        host_all: true
            
    - name: "Mariadb -Creating wordpress database {{ mysql_database }}"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_pass }}"
        name: "{{ mysql_database }}"
        state: present
            
    - name: "Mariadb  -Creating wordpress User {{ mysql_user }}"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_pass }}"
        name: "{{ mysql_user }}"
        host: "%"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_database }}.*:ALL"